### ISSUE TITLE
Online Demo not work

### ISSUE THREAD

**Issue by MiXaiLL76** [BradyFU/Woodpecker#1]
No interface is running right now

**Comment by xjtupanda** [comment]
Thanks for your interest. We've managed to coordinate GPU resources, and have just updated the link. You could have a try now!

**Comment by fs302** [comment]
Same Issue happens：https://f252626b321420bfb1.gradio.live/
![image](https://github.com/BradyFU/Woodpecker/assets/1341843/e36496fa-091d-4c6a-89f9-6a618d350b07)
