### ISSUE TITLE
Online Demo is off

### ISSUE THREAD

**Issue by fs302** [BradyFU/Woodpecker#10]
Same Issue happens：https://f252626b321420bfb1.gradio.live/
![image](https://github.com/BradyFU/Woodpecker/assets/1341843/e36496fa-091d-4c6a-89f9-6a618d350b07)

_Originally posted by @fs302 in https://github.com/BradyFU/Woodpecker/issues/1#issuecomment-1853869064_

**Comment by xjtupanda** [comment]
Thanks for your reminder! The link has been updated and should be fine now. Please note that the link is temporary and subject to regular maintenance.

**Comment by Deep1994** [comment]
I find the Online Demo is off, how can I get it?

**Comment by xjtupanda** [comment]
> I find the Online Demo is off, how can I get it?

Thanks for your attention. We've taken down the online demo due to limited resources. You may run the inference or set up a demo following the instructions on the main page.
