### ISSUE TITLE
How to reproduce results on POPE?

### ISSUE THREAD

**Issue by kai-wen-yang** [BradyFU/Woodpecker#11]
Could you please provide the script that can reproduce results on POPE?

**Comment by BradyFU** [comment]
Hi Kaiwen,
You can use our model to get the outputs, and it would be not difficult for you to calculate the indicators on POPE. Please feel free to contact me if you meet any questions.

**Comment by kai-wen-yang** [comment]
I don't know the hyperparameter (e.g. temperature) and prompt used when evaluating on POPE.

**Comment by xjtupanda** [comment]
> I don't know the hyperparameter (e.g. temperature) and prompt used when evaluating on POPE.

Thanks for your interest in our work. We used default hyperparameters for the whole setup, except that the `img_num` is set to 50 for POPE. Feel free to ask here or through other means.
