### ISSUE TITLE
License of woodpecker

### ISSUE THREAD

**Issue by papasanimohansrinivas** [BradyFU/Woodpecker#4]
License of woodpecker @BradyFU

**Comment by BradyFU** [comment]
Thanks for your reminder. It is free to use Woodpecker for academic research

**Comment by papasanimohansrinivas** [comment]
what about commercial usage of woodpecker weights and code @BradyFU

**Comment by BradyFU** [comment]
Now, it is only allowed for pure research usage. Thanks!
