### ISSUE TITLE
Evaluation code

### ISSUE THREAD

**Issue by unlabeledData** [BradyFU/Woodpecker#6]
I think it's a great work for MLLM. Nice idea. 
I'm sorry but I don't find evaluation code. Do you release the evaluation code? If not, will you release it?

**Comment by BradyFU** [comment]
Thanks for your attention! You can directly use our code to generate the results and use the provided evalation tools (e.g. MME https://github.com/BradyFU/Awesome-Multimodal-Large-Language-Models/tree/Evaluation/tools) to get the quantitative results. If you encounter any problems, please feel free to contact us.

**Comment by unlabeledData** [comment]
Thank you ~

**Comment by unlabeledData** [comment]
> Thanks for your attention! You can directly use our code to generate the results and use the provided evalation tools (e.g. MME https://github.com/BradyFU/Awesome-Multimodal-Large-Language-Models/tree/Evaluation/tools) to get the quantitative results. If you encounter any problems, please feel free to contact us.

Thank you~
