### ISSUE TITLE
indicator evaluation

### ISSUE THREAD

**Issue by Rh-Dang** [BradyFU/Woodpecker#7]
I am very interested in your work, could you please publish the code related to your indicator evaluation? Thanks very much!!!

**Comment by xjtupanda** [comment]
Thanks for your attention! Could you please specify which part, since 'indicator' evaluation is vague?

**Comment by Rh-Dang** [comment]
Thank you very much for your reply! The indicators I mentioned are some of the evaluation indicators that were quantitatively tested in your paper. like on POPE, MME benchmark and GPT-4V-aided evaluation. We would like to replicate your results on these benchmarks.

**Comment by xjtupanda** [comment]
You may follow the official evaluation protocol as we did. The repos for benchmarks provide evaluation tools to calculate metrics automatically.
- [POPE](https://github.com/BradyFU/Woodpecker/blob/main/assets/gpt4v_prompt.txt)
- [MME](https://github.com/BradyFU/Awesome-Multimodal-Large-Language-Models/tree/Evaluation/tools)
The prompt for GPT-4V-Aided Evaluation is available at [Link](https://github.com/BradyFU/Woodpecker/blob/main/assets/gpt4v_prompt.txt)
